title: D & K MEADOWS
description: Somerset Sheepery
author: Giuliana Taylor
logo: /static/img/sheep.png
github: 
about: A Somerset Sheepery

baseurl: ""
url: "https://dandkmeadows.com"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: 
  fb_appid: 


enableTags: false
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]